apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: $IMAGE_NAME
spec:
  template:
    spec:
      serviceAccountName: $CLOUD_RUN_SERVICE_ACCOUNT
      containers:
        - image: $REGISTRY_IMAGE:$GITHUB_SHA
          env:
            - name: NODE_ENV
              value: $NODE_ENV
            - name: CLIENT_ID
              value: "$CLIENT_ID"
            - name: DATABASE_NAME
              value: "$DATABASE_NAME"
            - name: DATABASE_PASSWORD
              value: "$DATABASE_PASSWORD"
            - name: DATABASE_USERNAME
              value: "$DATABASE_USERNAME"
            - name: DATABASE_REGION
              value: "$DATABASE_REGION"
            - name: DATABASE_PROJECT
              value: "$DATABASE_PROJECT"
            - name: DATABASE_INSTANCE
              value: "$DATABASE_INSTANCE"
            - name: HOST_DB
              value: "$HOST_DB"
            - name: PORT_DB
              value: "$PORT_DB"
            - name: PRIVATE_KEY
              value: $PRIVATE_KEY
            - name: PROJECT_ID
              value: "$PROJECT_ID"
            - name: SERVER_PORT
              value: "$SERVER_PORT"
            - name: CLIENT_EMAIL
              value: "$CLIENT_EMAIL"
            - name: MAIL_HOST
              value: "$MAIL_HOST"
            - name: MAIL_PORT
              value: "$MAIL_PORT"
            - name: MAIL_USERNAME
              value: "$MAIL_USERNAME"
            - name: MAIL_PASSWORD
              value: "$MAIL_PASSWORD"
            - name: MAIL_SMPT_CONNECTIONTIMEOUT
              value: "$MAIL_SMPT_CONNECTIONTIMEOUT"
            - name: MAIL_SMPT_WRITETIMEOUT
              value: "$MAIL_SMPT_WRITETIMEOUT"
            - name: MAIL_SMPT_AUTH
              value: "$MAIL_SMPT_AUTH"
            - name: MAIL_SMPT_STARTTLS_ENABLE
              value: "$MAIL_SMPT_STARTTLS_ENABLE"
            - name: MAIL_SMPT_STARTTLS_REQUIRED
              value: "$MAIL_SMPT_STARTTLS_REQUIRED"
