db:
  port: ${PORT_DB}
  database: ${DATABASE_NAME}
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}
  project: ${DATABASE_PROJECT}
  region: ${DATABASE_REGION}
  instance: ${DATABASE_INSTANCE}
  url: "r2dbc:gcp:postgres://${db.username}:${db.password}@${db.project}:${db.region}:${db.instance}/${db.database}"


bigquery:
  project-id: ${PROJECT_ID}
  client-id: ${CLIENT_ID}
  client-email: ${CLIENT_EMAIL}
  private-key: ${PRIVATE_KEY}
server:
  port: ${SERVER_PORT}


logging:
  level:
    org:
      springframework: INFO