db:
  host: ${HOST_DB}
  port: ${PORT_DB}
  database: ${DATABASE_NAME}
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}

bigquery:
  project-id: ${PROJECT_ID}
  client-id: ${CLIENT_ID}
  client-email: ${CLIENT_EMAIL}
  private-key: ${PRIVATE_KEY}
server:
  port: ${SERVER_PORT:8080}

spring:
  r2dbc:
    url: "r2dbc:postgresql://${db.host}:5432/${db.database}"
    username: ${db.username}
    password: ${db.password}

logging:
  level:
    org:
      springframework: INFO